# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'The Product Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for The Product Project

  target 'The Product ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'The Product ProjectUITests' do
    # Pods for testing
  end

end
